# DS-NYC-45 | Final Project 4: Modeling Performance

In [3]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import sklearn as skl

pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)

%matplotlib inline
plt.style.use('ggplot')

In [4]:
users = pd.read_csv(os.path.join('project_dataset', 'user_data.csv'), index_col='user_id')
res = pd.read_csv(os.path.join('project_dataset', 'reservations_data.csv'), index_col='user_id')


In [5]:
df = pd.concat([users, res], axis=1, join_axes=[users.index])

df.head()

is_converted  lead_created_month  lead_created_day_of_week  \
user_id                                                               
12                  0                   5                         4   
14                  0                   5                         5   
15                  1                   6                         1   
16                  1                   7                         3   
23                  1                   6                         1   

         is_paidsocial_lead  is_organic_lead  lead_msa_id  is_seo_studios  \
user_id                                                                     
12                        0                1        1.000               0   
14                        0                1        1.000               0   
15                        0                1        1.000               0   
16                        0                1        1.000               0   
23                        0                1        1.000               0   

         is_inviteafriend  is_email  is_referral  is_paidsocial  \
user_id                                                           
12                      0         0            0              0   
14                      0         0            0              0   
15                      0         0            0              0   
16                      0         0            0              0   
23                      0         0            0              0   

        marketing_channel  is_organic  user_acquisition_month  \
user_id                                                         
12              Sell Page           1                   9.000   
14              Sell Page           1                   9.000   
15                 Mobile           1                   9.000   
16              Sell Page           1                   8.000   
23              Sell Page           0                   8.000   

         user_acquisition_day_of_week  promo_days  lead_to_promo_days  \
user_id                                                                 
12                              3.000         nan                   0   
14                              3.000         nan                   0   
15                              1.000         nan                   0   
16                              4.000         nan                   0   
23                              3.000      30.000                 429   

         is_three_studio_visits  is_two_studio_visits  is_four_studio_visits  \
user_id                                                                        
12                            1                     0                      0   
14                            1                     0                      0   
15                            0                     1                      0   
16                            1                     0                      0   
23                            0                     1                      0   

        acquisition_plan_category    zip  is_onboarded  user_country  \
user_id                                                                
12               CP Complimentary  10001             1         1.000   
14               CP Complimentary  10009             1         1.000   
15                        CP Base  10003             1         1.000   
16                   CP Unlimited    NaN             1         1.000   
23                        CP Base  30363             1         1.000   

         user_msa_id promo_alias parent_promo promo_category  \
user_id                                                        
12             1.000    no_promo     no_promo       no_promo   
14             1.000    no_promo     no_promo       no_promo   
15             1.000    no_promo     no_promo       no_promo   
16             1.000    no_promo     no_promo       no_promo   
23             1.000      aug1fb  dollarpromo          trial   

         is_commit

In [6]:
df = df.fillna(0)
df.head()

is_converted  lead_created_month  lead_created_day_of_week  \
user_id                                                               
12                  0                   5                         4   
14                  0                   5                         5   
15                  1                   6                         1   
16                  1                   7                         3   
23                  1                   6                         1   

         is_paidsocial_lead  is_organic_lead  lead_msa_id  is_seo_studios  \
user_id                                                                     
12                        0                1        1.000               0   
14                        0                1        1.000               0   
15                        0                1        1.000               0   
16                        0                1        1.000               0   
23                        0                1        1.000               0   

         is_inviteafriend  is_email  is_referral  is_paidsocial  \
user_id                                                           
12                      0         0            0              0   
14                      0         0            0              0   
15                      0         0            0              0   
16                      0         0            0              0   
23                      0         0            0              0   

        marketing_channel  is_organic  user_acquisition_month  \
user_id                                                         
12              Sell Page           1                   9.000   
14              Sell Page           1                   9.000   
15                 Mobile           1                   9.000   
16              Sell Page           1                   8.000   
23              Sell Page           0                   8.000   

         user_acquisition_day_of_week  promo_days  lead_to_promo_days  \
user_id                                                                 
12                              3.000       0.000                   0   
14                              3.000       0.000                   0   
15                              1.000       0.000                   0   
16                              4.000       0.000                   0   
23                              3.000      30.000                 429   

         is_three_studio_visits  is_two_studio_visits  is_four_studio_visits  \
user_id                                                                        
12                            1                     0                      0   
14                            1                     0                      0   
15                            0                     1                      0   
16                            1                     0                      0   
23                            0                     1                      0   

        acquisition_plan_category    zip  is_onboarded  user_country  \
user_id                                                                
12               CP Complimentary  10001             1         1.000   
14               CP Complimentary  10009             1         1.000   
15                        CP Base  10003             1         1.000   
16                   CP Unlimited      0             1         1.000   
23                        CP Base  30363             1         1.000   

         user_msa_id promo_alias parent_promo promo_category  \
user_id                                                        
12             1.000    no_promo     no_promo       no_promo   
14             1.000    no_promo     no_promo       no_promo   
15             1.000    no_promo     no_promo       no_promo   
16             1.000    no_promo     no_promo       no_promo   
23             1.000      aug1fb  dollarpromo          trial   

         is_commit

In [7]:
df.shape

(586207, 49)

In [12]:
df.dtypes

['is_converted',
 'lead_created_month',
 'lead_created_day_of_week',
 'is_paidsocial_lead',
 'is_organic_lead',
 'lead_msa_id',
 'is_seo_studios',
 'is_inviteafriend',
 'is_email',
 'is_referral',
 'is_paidsocial',
 'marketing_channel',
 'is_organic',
 'user_acquisition_month',
 'user_acquisition_day_of_week',
 'promo_days',
 'lead_to_promo_days',
 'is_three_studio_visits',
 'is_two_studio_visits',
 'is_four_studio_visits',
 'acquisition_plan_category',
 'zip',
 'is_onboarded',
 'user_country',
 'user_msa_id',
 'promo_alias',
 'parent_promo',
 'promo_category',
 'is_commitment_plan',
 'avg_class_rating',
 'avg_days_from_booking_to_class',
 'avg_peak_classes',
 'reservations_attended_barre_count',
 'reservations_attended_boxing_count',
 'reservations_attended_cycling_count',
 'reservations_attended_dance_count',
 'reservations_attended_gym_count',
 'reservations_attended_martial_arts_count',
 'reservations_attended_pilates_count',
 'reservations_attended_rowing_count',
 'reservations_at

In [7]:
# turn categorical into numbers
# marketing_channel_dum = pd.get_dummies(df['marketing_channel'], drop_first=True).astype(int)
# acquisition_plan_category_dum = pd.get_dummies(df['acquisition_plan_category'], drop_first=True).astype(int)
# promo_alias_dum = pd.get_dummies(df['promo_alias'], drop_first=True).astype(int)
# parent_promo_dum = pd.get_dummies(df['parent_promo'], drop_first=True).astype(int)
# promo_category_dum = pd.get_dummies(df['promo_category'], drop_first=True).astype(int)
# zip_dum = pd.get_dummies(df['zip'], drop_first=True).astype(int)

# df_dummies = pd.concat([marketing_channel_dum,acquisition_plan_category_dum,promo_alias_dum,parent_promo_dum,promo_category_dum,zip_dum])

# df_dummies

# pd.get_dummies(data=df, columns=['marketing_channel', 'acquisition_plan_category','promo_alias','parent_promo','promo_category','zip'], drop_first=True)

In [8]:
# df = pd.get_dummies(data=df, columns=['promo_alias'], prefix='promo', drop_first=True)

In [ ]:
df.drop(['marketing_channel', 'acquisition_plan_category', 'promo_alias','parent_promo','promo_category','zip'], axis=1, inplace=True)

In [ ]:
X = df.drop('is_converted', axis=1)
y = df['is_converted'].astype(int)

In [10]:
X.head()

lead_created_month  lead_created_day_of_week  is_paidsocial_lead  \
user_id                                                                     
12                        5                         4                   0   
14                        5                         5                   0   
15                        6                         1                   0   
16                        7                         3                   0   
23                        6                         1                   0   

         is_organic_lead  lead_msa_id  is_seo_studios  is_inviteafriend  \
user_id                                                                   
12                     1        1.000               0                 0   
14                     1        1.000               0                 0   
15                     1        1.000               0                 0   
16                     1        1.000               0                 0   
23                     1        1.000               0                 0   

         is_email  is_referral  is_paidsocial  is_organic  \
user_id                                                     
12              0            0              0           1   
14              0            0              0           1   
15              0            0              0           1   
16              0            0              0           1   
23              0            0              0           0   

         user_acquisition_month  user_acquisition_day_of_week  promo_days  \
user_id                                                                     
12                        9.000                         3.000       0.000   
14                        9.000                         3.000       0.000   
15                        9.000                         1.000       0.000   
16                        8.000                         4.000       0.000   
23                        8.000                         3.000      30.000   

         lead_to_promo_days  is_three_studio_visits  is_two_studio_visits  \
user_id                                                                     
12                        0                       1                     0   
14                        0                       1                     0   
15                        0                       0                     1   
16                        0                       1                     0   
23                      429                       0                     1   

         is_four_studio_visits  is_onboarded  user_country  user_msa_id  \
user_id                                                                   
12                           0             1         1.000        1.000   
14                           0             1         1.000        1.000   
15                           0             1         1.000        1.000   
16                           0             1         1.000        1.000   
23                           0             1         1.000        1.000   

         is_commitment_plan  avg_class_rating  avg_days_from_booking_to_class  \
user_id                                                                         
12                    0.000             0.000                           0.000   
14                    0.000             0.000                           0.000   
15                    0.000             0.000                           0.000   
16                    0.000             0.000                           0.000   
23                    0.000             5.000                           1.250   

         avg_peak_classes  reservations_attended_barre_count  \
user_id                                                        
12                  0.000                              0.000   
14                  0.000                              0.000   
15                  0.000                              0.000   
16                  0

In [11]:
y.head()

user_id
12    0
14    0
15    1
16    1
23    1
Name: is_converted, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [44]:
# univariate selection

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# feature extraction
kbest = SelectKBest(score_func=chi2, k=4)
fit = kbest.fit(X, y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
np.set_printoptions(precision= 3, suppress=True)
print(features[0:5,:])

[ 204995.       3015.059     171.54     3897.765      29.794   87611.539
     221.254   10752.022     941.288      73.009   21131.901   71926.337
    6482.763     363.623  899185.844  434558.185   20780.659   38253.036
     451.322   10412.239    3202.713   88211.826    5121.108  116951.074
   49509.729   20753.591      99.064    1444.181     563.72      934.874
    1564.459     319.238      75.469     111.29     1168.827    2081.548
    1246.775     237.055    2928.206    3351.292    1966.238      29.674
   51395.649]
[[   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   1.    0.    0.    0.]
 [   1.    0.    0.    0.]
 [   1.   30.  429.    5.]]


In [56]:
# Feature Extraction with RFE
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# feature extraction
logreg = LogisticRegression()
rfe = RFE(logreg, 10)
fit = rfe.fit(X, y)
print("Num Features: %d") % fit.n_features_
print("Selected Features: %s") % fit.support_
print("Feature Ranking: %s") % fit.ranking_

Num Features: 10
Selected Features: [ True False False  True  True False False False False False  True  True
 False False False False  True  True  True False  True False False False
 False  True False False False False False False False False False False
 False False False False False False False]
Feature Ranking: [ 1 10  6  1  1 22 17  2  4 26  1  1 23 11 25 33  1  1  1  3  1 34  7  5 12
  1 27 20 28 24  9 19  8 30 32 29 16 15 21 14 13 18 31]


In [28]:
# Feature Extraction with PCA
from sklearn.decomposition import PCA

# feature extraction
pca = PCA(n_components=3)
fit = pca.fit(X)
# summarize components
print("Explained Variance: %s") % fit.explained_variance_ratio_
print(fit.components_)

Explained Variance: [ 0.777  0.19   0.021]
[[ -1.436e-04  -5.744e-04   5.167e-05   1.249e-05  -1.104e-04  -3.606e-03
    7.470e-07  -1.047e-05   2.021e-04   1.395e-05   1.086e-04  -4.337e-04
   -8.340e-05   7.120e-05   2.495e-02   9.979e-01  -2.793e-04   2.771e-04
    4.169e-06   7.839e-05  -1.489e-04  -2.695e-03   1.993e-04   2.404e-03
    1.002e-03   3.214e-04   8.803e-04   1.559e-04   9.656e-04   2.569e-04
    2.744e-05   5.657e-05   9.104e-04   1.097e-04   1.457e-03   7.971e-04
    2.459e-03   1.198e-03   5.043e-04   4.343e-03   9.185e-05   2.406e-04
    5.989e-02]
 [ -2.430e-04  -3.861e-04   1.351e-04   3.079e-04  -2.344e-04   1.901e-03
   -1.020e-05  -7.403e-05   8.335e-04   2.695e-04   4.998e-04  -2.281e-03
   -1.542e-03   5.238e-04   1.998e-01  -6.397e-02   6.267e-05  -7.999e-05
    5.956e-05  -4.953e-04   2.968e-04   1.540e-03   1.607e-03   1.587e-02
    6.865e-03   1.942e-03   1.266e-02   2.876e-03   1.407e-02   4.196e-03
    5.225e-04   1.111e-03   1.575e-02   1.392e-03   2.

In [ ]:
import pandas
from pandas.tools.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [10]:
# Split-out validation dataset
from sklearn import model_selection
X = X
Y = y
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [ ]:
# Test options and evaluation metric
seed = 7
scoring = 'accuracy'

In [ ]:
#Spot Check Algorithms
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
	kfold = model_selection.KFold(n_splits=10, random_state=seed)
	cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
	results.append(cv_results)
	names.append(name)
	msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
	print(msg)

In [27]:
from slearn.linear_model import Lasso

In [31]:
lasso = Lasso(alpha=0.00001, normalize=True)

In [32]:
lasso.fit(X, y)

Lasso(alpha=1e-05, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [33]:
lasso.coef_

array([ 0.98394458,  0.        , -0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.        ,  0.        ,  0.        ,
       -0.        ,  0.        ,  0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        ,  0.        ,  0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ,  0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        ,  0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        , -0.        , -0.        ,
        0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.  

In [ ]:
def lasso_regression(data, predictors, alpha, models_to_plot={}):
    #Fit the model
    lassoreg = Lasso(alpha=alpha,normalize=True, max_iter=1e5)
    lassoreg.fit(X,y)
    y_pred = lassoreg.predict(df['is_converted'])
    
    #Check if a plot is to be made for the entered alpha
    if alpha in models_to_plot:
        plt.subplot(models_to_plot[alpha])
        plt.tight_layout()
        plt.plot(X,y_pred)
        plt.plot(X,y,'.')
        plt.title('Plot for alpha: %.3g'%alpha)
    
    #Return the result in pre-defined format
    rss = sum((y_pred-y)**2)
    ret = [rss]
    ret.extend([lassoreg.intercept_])
    ret.extend(lassoreg.coef_)
    return ret

In [2]:
# 20 cross validation iterations with 30% test / 70% train
from sklearn.model_selection import ShuffleSplit
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)

from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
# transform our training features
X_train_std = stdsc.fit_transform(X_train)
# transform the testing features in the same way
X_test_std = stdsc.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,weights='uniform', p=2)

NameError: name 'X_train' is not defined

In [ ]:

# search for an optimal value of K for KNN
k_range = list(range(1, 41))
k_scores = []
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train_std, y, cv=10, scoring='accuracy')
    k_scores.append(scores.mean())
print(k_scores)

In [ ]:

import matplotlib.pyplot as plt
%matplotlib inline

# plot the value of K for KNN (x-axis) versus the cross-validated accuracy (y-axis)
plt.plot(k_range, k_scores)
plt.xlabel('Value of K for KNN')
plt.ylabel('Cross-Validated Accuracy')

In [1]:
from sklearn.grid_search import GridSearchCV

# define the parameter values that should be searched
k_range = list(range(1, 41))
leaf_size_range = list(range(20, 50))

param_grid = dict(n_neighbors=k_range, leaf_size=leaf_size_range)
grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')
grid.fit(X, y)
grid_mean_scores = [result.mean_validation_score for result in grid.grid_scores_]

print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

/Users/MacKenzie/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/MacKenzie/anaconda/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


NameError: name 'knn' is not defined

In [ ]:
# 10-fold cross-validation with K=31 for KNN
knn = KNeighborsClassifier(n_neighbors=21, leaf_size=20)
scores = cross_val_score(knn, X, y, cv=10, scoring='roc_auc')

print(scores.mean())